# CodeRabbit Configuration
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  
  tools:
    ast-grep:
      enabled: true
    ruff:
      enabled: true

  path_filters:
    - "!data/**"
    - "!logs/**"
    - "!venv/**"
    - "!**/*.png"
    - "!**/*.json"

chat:
  auto_reply: true
